document.writeln("<div id=\"menu\" style=\"position:fixed;bottom:0px;width:100%;height:44px;line-height:44px;z-index:999;background:url(images/menubg.png) repeat-x;\">");
document.writeln("<ul style=\"margin:0 auto;list-style-type:none;width:100%;max-width:500px;height:100%;\">");
document.writeln("<li><img class=\"img_front\" src=\"images/front.png\"><div class=\"menu_li\">产品中心</div><img class=\"line\" src=\"images/line.png\" width=1>");
document.writeln("<span style=\"background-size:100%;\">");
document.writeln("<img src=\"images/navbg7.png\" width=100%>");
document.writeln("<div style=\"position:absolute;top:0px;left:0px;\">");
document.writeln("<a href=\"s1.html\">云POS S1</a>");
document.writeln("<a href=\"s2.html\">云POS S2</a>");
document.writeln("<a href=\"S3.html\">云POS S3</a>");
document.writeln("<a href=\"p1.html\">云POS P1</a>");
document.writeln("<a href=\"pcsy.html\">PC收银</a>");
document.writeln("<a href=\"2v.html\">二维码支付</a>");
document.writeln("<a href=\"jiandan.html\">简单付</a>");
document.writeln("</div>");
document.writeln("</span>");
document.writeln("</li>");
document.writeln("<li><img class=\"img_front\" src=\"images/front.png\"><div class=\"menu_li\">营销O2O</div><img class=\"line\" src=\"images/line.png\" width=1>");
document.writeln("<span style=\"background-size:100%;\">");
document.writeln("<img src=\"images/navbg3.png\" width=100%>");
document.writeln("<div style=\"position:absolute;top:0px;left:0px;\">");
document.writeln("<a href=\"qq.html\">轻券</a>");
document.writeln("<a href=\"hyxt.html\">会员系统</a>");
document.writeln("<a href=\"zhsq.html\">智慧商圈</a>");
document.writeln("</div>");
document.writeln("</span>");
document.writeln("</li>");
document.writeln("<li><img class=\"img_front\" src=\"images/front.png\"><div class=\"menu_li\">优惠政策</div><img class=\"line\" src=\"images/line.png\" width=1>");
document.writeln("<span style=\"background-size:100%;\">");
document.writeln("<img src=\"images/navbg3.png\" width=100%>");
document.writeln("<div style=\"position:absolute;top:0px;left:0px;\">");
document.writeln("<a href=\"hyfx.html\">行业分析</a>");
document.writeln("<a href=\"yhzx.html\">优惠政策</a>");
document.writeln("<a href=\"jiamengwomen\">加盟申请</a>");
document.writeln("</div>");
document.writeln("</span>");
document.writeln("</li>");
document.writeln("<li><img class=\"img_front\" src=\"images/front.png\"><div class=\"menu_li\">集团实力</div><img class=\"line\" src=\"images/line.png\" width=1>");
document.writeln("<span style=\"background-size:100%;\">");
document.writeln("<img src=\"images/navbg6.png\" width=100%>");
document.writeln("<div style=\"position:absolute;top:0px;left:0px;\">");
document.writeln("<a href=\"jtjj.html\">集团简介</a>");
document.writeln("<a href=\"jtry.html\">集团荣誉</a>");
document.writeln("<a href=\"fzlc.html\">发展历程</a>");
document.writeln("<a href=\"qdal.html\">渠道案例</a>");
document.writeln("<a href=\"xsyx.html\">销售一线</a>");
document.writeln("<a href=\"shgy.html\">社会公益</a>");
document.writeln("</div>");
document.writeln("</span>");
document.writeln("</li>");
document.writeln("<li><img class=\"img_front\" src=\"images/front.png\"><div class=\"menu_li\">查询服务</div>");
document.writeln("<span style=\"background-size:100%;\">");
document.writeln("<img src=\"images/navbg3.png\" width=100% style=\"margin-bottom: -43px;\">");
document.writeln("<div style=\"position:absolute;top:0px;left:0px;\">");
document.writeln("<a href=\"http://pay5858.com/qmdx\">轻妹大学</a>");
document.writeln("<a href=\"http://www.pay5858.com/qmdx/cx.html\">授权查询</a>");
document.writeln("<a href=\"http://pay5858.com/qmdx/sjxz.html\">APP下载</a>");
document.writeln("</div>");
document.writeln("</span>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("</div>");
document.writeln("<script type=\'text/javascript\' src=\'//s.union.360.cn/55896.js\'></script>");
document.writeln("<script>");
document.writeln("var _hmt = _hmt || [];");
document.writeln("(function() {");
document.writeln("  var hm = document.createElement(\'script\');");
document.writeln("  hm.src = \'//hm.baidu.com/hm.js?c60f026045c1acfa7211f783928803d7\';");
document.writeln("  var s = document.getElementsByTagName(\'script\')[0]; ");
document.writeln("  s.parentNode.insertBefore(hm, s);");
document.writeln("})();");
document.writeln("</script>");